# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "25.x"

    - name: Build
      run: make build-proto

    - name: Change go module
      run: |
        mkdir v2
        directory=$(find . -type d -not -path '*/.*' | grep -E "./" | grep -v "v2")
        mv $directory v2/
        cp go.mod v2/
        go mod edit -module github.com/make-money-fast/pb/v2 v2/go.mod

    - name: Commit files
      run: |
        git config --local user.email "gitrobot@clearcode.cn"
        git config --local user.name "gitrobot"
        git add . 
        git commit -a -m "build proto files"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: v2
        force: true